apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops-training
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: pun-api
          image: ghcr.io/danyouknowme/devops-cicd:a2760b4c8d381c1b5a7e9e6ff94637a1ceed0c47
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: api.service.port
